package peanuty.framework.taglib;

import javax.servlet.jsp.*;


public class Button
    extends BaseTagLib {

    private String type;
    private String name;
    private String value;
    private String onClick;
    private String style = null;

    public final void setName(String name) {
        this.name = name;
    }

    public final void setType(String type) {
        this.type = type;
    }

    public final void setValue(String value) {
        this.value = value;
    }

    public final void setOnClick(String onClick) {
        this.onClick = onClick;
    }

    public void setStyle(String style) {
        this.style = style;
    }


    public final int doEndTag() throws JspException {
        write(composeSelectString());
        return EVAL_PAGE;
    }

    private String composeSelectString() {
        StringBuffer s = new StringBuffer();
        s.append("<!-- generated by webapp.framework.taglib.Select -->\n");
        s.append("<input type = '").append(type).append("'");
        s.append(getCSSClass("Button"));
        if(style != null){
            s.append(" style = '").append(style).append("'");
        }
        if(name != null){
            s.append(" name = '").append(name).append("'");
        }
        if(onClick != null){
            s.append(" onClick = '").append(onClick).append("'");
        }
        s.append(" value = '").append(value).append("'");
        s.append("/>\n");
        return s.toString();
    }
}
