package peanuty.framework.taglib;

import java.util.Map;
import peanuty.framework.util.*;

public class Checkboxes
    extends BaseTagLib {
    public final void setName(String name) {
        this.name = name;
    }

    public final void setSrc(Map src) {
        this.src = src;
    }

    public final void setCheckboxVal(String checkboxVal) {
        this.checkboxVal = checkboxVal;
    }

    public final void setCheckboxTxt(String checkboxTxt) {
        this.checkboxTxt = checkboxTxt;
    }

    public final void setCheckedVal(String checkedVal) {
        this.checkedVal = checkedVal;
    }

    private String composeCheckboxString() {
        int i;
        StringBuffer s = new StringBuffer();
        s.append("<!-- generated by webapp.framework.taglib.Checkboxes -->\n");
        s.append("<table width=\"100%\" border=\"0\">");
        s.append("<tr>");
        for (i = 0; i < src.size(); i++) {
            Map item = (Map) src.get("ROW" + i);
            if (i % 3 == 0 && i != 0) {
                s.append("</tr><tr>");
            }
            s.append("<td><input type=\"checkbox\" name=\"");
            s.append(name);
            s.append("\" value=\"");
            s.append(DataFilter.wohs(item, checkboxVal));
            s.append("\"");
            s.append(getCSSClass("checkbox"));
            checkedVal = "," + checkedVal + ",";
            if (checkedVal.indexOf("," + DataFilter.show(item, checkboxVal) + ",") !=
                -1) {
                s.append(" checked");
            }
            s.append(">&nbsp;");
            s.append(DataFilter.wohs(item, checkboxTxt));
            s.append("</td>");
        }
        for (int j = 0; j < 3 - i % 3; j++) {
            s.append("<td>&nbsp;</td>");
        }
        s.append("</tr></table>");
        return s.toString();
    }

    public int doEndTag() {
        write(composeCheckboxString());
        return EVAL_PAGE;
    }

    private String name;
    private Map src;
    private String checkboxVal;
    private String checkboxTxt;
    private String checkedVal;
}
